locale: fr

backend:
  name: test-repo
  branch: main

# local_backend: true

media_folder: "public/uploads" # Où les images sont stockées
public_folder: "/uploads" # URL publique des images

collections:
  - label: "Articles"
    name: "articles"
    editor:
      preview: false
    folder: "src/content/articles"
    create: true
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "tags",
          search_fields: ["title"],
          display_fields: ["title"],
          value_field: "{{slug}}",
          multiple: true,
          hint: "Sélectionnez les tags associés à l'article (minimum 1, maximum 3)",
        }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Introduction", name: "intro", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - label: "Tags"
    name: "tags"
    editor:
      preview: false
    folder: "src/content/tags"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }

  - label: "Événements"
    name: "events"
    editor:
      preview: false
    folder: "src/content/events"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Introduction", name: "intro", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Lieu", name: "location", widget: "string" }
      - { label: "Lien", name: "link", widget: "string", required: false }

  - label: "Disciples"
    name: "members"
    editor:
      preview: false
    folder: "src/content/members"
    create: true
    identifier_field: "name"
    slug: "{{slug}}-{{minute}}-{{second}}"
    fields:
      - { label: "Nom et Prénom", name: "name", widget: "string" }
      - {
          label: "Couleur de l'écharpe",
          name: "color",
          widget: "select",
          options:
            [
              { label: "Ami des Escoffiers", value: "#1e40af" },
              { label: "Fournisseurs", value: "#15803d" },
              { label: "Hôtelier", value: "#8b5cf6" },
              { label: "Cuisinier", value: "#b91c1c" },
            ],
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Rôle", name: "role", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Restaurant ou Lieu de travail",
          name: "workplace",
          widget: "string",
          required: false,
        }
      - { label: "Email", name: "email", widget: "string", required: false }
      - {
          label: "A l'honneur",
          name: "is_honored",
          widget: "boolean",
          required: false,
        }

  - label: "Configuration"
    name: "featured"
    editor:
      preview: false
    delete: false
    create: false
    files:
      - label: "Article à la une"
        name: "highlighted"
        file: "src/content/settings/featured.md"
        fields:
          - {
              label: "Article à la une",
              name: "slug",
              widget: "relation",
              collection: "articles",
              search_fields: ["title"],
              display_fields: ["title"],
              value_field: "{{slug}}",
            }
