locale: fr

backend:
  name: test-repo
  branch: main

media_folder: "public/uploads" # Où les images sont stockées
public_folder: "/uploads" # URL publique des images

collections:
  - name: "tags"
    label: "Catégories Articles"
    folder: "src/content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Couleur", name: "color", widget: "color", required: false }

  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Extrait", name: "excerpt", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Catégorie",
          name: "category",
          widget: "relation",
          collection: "tags",
          value_field: "slug",
          search_fields: ["name"],
          display_fields: ["name"],
        }
      - { label: "Image", name: "image", widget: "image" }

  - name: "article-a-la-une"
    label: "Article à la une"
    delete: false
    editor:
      preview: false
    files:
      - label: "Article à la une"
        name: "featured"
        file: "src/content/articles/featured.md"
        fields:
          - label: "Article sélectionné"
            name: "slug"
            widget: "relation"
            collection: "articles"
            value_field: "slug"
            search_fields: ["title", "slug"]
            display_fields: ["title"]

  - name: "evenements"
    label: "Événements"
    folder: "src/content/evenements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Extrait", name: "excerpt", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Heure", name: "time", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Lien externe",
          name: "externalLink",
          widget: "string",
          required: false,
        }
